apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: talant
  name: talant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: talant
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
